#!/data/data/com.termux/files/usr/bin/bash

clear

cd ~

rm -rff ~/SignGen

cd ~

git clone https://github.com/xpert0/SignGen

cd ~

clear

echo "\e[1;32m Run ' bash ~/SignGen/convert ' to use the tool \e[0m"
