#!/data/data/com.termux/files/usr/bin/bash

clear

cd ~

rm -rff ~/SignGen

cd ~

git clone https://github.com/xpert01/SignGen

cd ~

clear

echo -e "\e[1;32m SUCCESS \e[0m"

echo -e "\e[1;32m Run ' bash ~/SignGen/convert ' if you want to use the tool now \e[0m"

cd ~
